import CreateListingForm from "@/components/Listings/CreateListingForm";
import Head from "next/head";
import React from "react";

type CreateListingProps = {};

const CreateListing: React.FC<CreateListingProps> = () => {
  return (
    <>
      <Head>
        <title>Create Listing - HomeHaven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CreateListingForm />
    </>
  );
};
export default CreateListing;
