import Cities from "@/components/Cities/Cities";
import Featured from "@/components/Featured/Featured";
import Hero from "@/components/Hero/Hero";
import Testimonials from "@/components/Testimonials/Testimonials";
import { Box } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <Box paddingBottom="600px">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Featured />
      <Cities />
      <Testimonials />
    </Box>
  );
}
